SELECT distinct *
INTO ALL_PAT_LIST
FROM(
	SELECT 
		A.CHR_NO, A.ID_NO, A.FST_OPD_DATE, B.FEE_NO, B.DEAD_DATE, 'W' AS HOS_GROUP
	FROM DBO.v_chr_basic_w A
	INNER JOIN DBO.v_chr_icd_w B
	ON A.CHR_NO = B.CHR_NO
UNION ALL
	SELECT 
		A.CHR_NO, A.ID_NO, A.FST_OPD_DATE, B.FEE_NO, B.DEAD_DATE, 'T' AS HOS_GROUP
	FROM DBO.v_chr_basic_t A
	INNER JOIN DBO.v_chr_icd_t B
	ON A.CHR_NO = B.CHR_NO
UNION ALL
	SELECT 
		A.CHR_NO, A.ID_NO, A.FST_OPD_DATE, B.FEE_NO, B.DEAD_DATE, 'S' AS HOS_GROUP
	FROM DBO.v_chr_basic_S A
	INNER JOIN DBO.v_chr_icd_S B
	ON A.CHR_NO = B.CHR_NO
) AS T

SELECT distinct A.*, B.D_DATE 
INTO ALL_PAT_DEAD_LIST
FROM ALL_PAT_LIST A
LEFT JOIN DBO.v_ndr_case B
ON A.ID_NO = B.ID_NO

SELECT distinct *
INTO LUNGCA_ALL_LIST
FROM(
	SELECT 
		B.*, A.SEX_TYPE, A.IPD_DATE,
		A.CPD_DATE, A.EDIAG_CODE, A.MDIAG_CODE, A.ICD10_CODE1, 
		A.ICD10_CODE1_OUT, A.FTEEN_FLAG, A.WEIGHT AS WEIGHT_1
	FROM ALL_PAT_DEAD_LIST B
	INNER JOIN DBO.v_ipd_basic_T A
	ON A.FEE_NO = B.FEE_NO
	AND A.CHR_NO = B.CHR_NO
UNION ALL
	SELECT 
		B.*, A.SEX_TYPE, A.IPD_DATE,
		A.CPD_DATE, A.EDIAG_CODE, A.MDIAG_CODE, A.ICD10_CODE1, 
		A.ICD10_CODE1_OUT, A.FTEEN_FLAG, A.WEIGHT AS WEIGHT_1
	FROM ALL_PAT_DEAD_LIST B
	INNER JOIN DBO.v_ipd_basic_S A
	ON A.FEE_NO = B.FEE_NO
	AND A.CHR_NO = B.CHR_NO
UNION ALL
	SELECT 
		B.*, A.SEX_TYPE, A.IPD_DATE,
		A.CPD_DATE, A.EDIAG_CODE, A.MDIAG_CODE, A.ICD10_CODE1, 
		A.ICD10_CODE1_OUT, A.FTEEN_FLAG, A.WEIGHT AS WEIGHT_1
	FROM ALL_PAT_DEAD_LIST B
	INNER JOIN DBO.v_ipd_basic_W A
	ON A.FEE_NO = B.FEE_NO
	AND A.CHR_NO = B.CHR_NO
) AS Q
WHERE 
Q.EDIAG_CODE LIKE '162.[234589]%' 
OR Q.ICD10_CODE1 LIKE 'C34.[012389][012]'



select *
from DBO.v_cr_tcase



--OR Q.MDIAG_CODE LIKE '162.[234589]%'
--OR Q.ICD10_CODE1_OUT LIKE 'C34.[012389][012]'

SELECT DISTINCT B.*, A.BIRTH_DT AS BIRTH_DT, A.CONT_DT, A.HISTBEH, A.CSTAGE,
	A.SMOKING, A.BTCHEW, A.DRINKING, A.DIAG_DT,
	A.LATERAL, A.HEIGHT, A.WEIGHT, A.FC_DT, A.STS_DT, A.OP_DT, A.CH, A.CH_O, A.CH_DT,
	A.HORM_O, A.HORM, A.HORM_DT, A.IMMU_O, A.IMMU, A.IMMU_DT, A.TARGET, A.TARGET_O, A.TARGET_DT,
	A.RTB_DT, A.SEQ_NO, A.RECUR
INTO LUNGCA_TUMOR_DATA
FROM LUNGCA_ALL_LIST B
INNER JOIN DBO.v_cr_tcase A
ON B.CHR_NO = A.CHR_NO
AND A.ID_NO = B.ID_NO
WHERE A.CASITE LIKE 'C34%'
--AND A.SEQ_NO LIKE '01'

SELECT *
FROM DBO.v_cr_tcase

SELECT DISTINCT A.*,
CASE WHEN B.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'HT',
CASE WHEN B1.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'DM_WITHOUT_1',
CASE WHEN B2.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'HLP',
CASE WHEN B3.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'CPD_1',
CASE WHEN B4.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'RENAL_2',
CASE WHEN B5.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'MI_1',
CASE WHEN B6.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'CHF_1',
CASE WHEN B7.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'CERE_1',
CASE WHEN B8.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'DEME_1',
CASE WHEN B9.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'RHEUM_1',
CASE WHEN B10.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'PEPTIC_1',
CASE WHEN B11.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'MILD_LIVER_1',
CASE WHEN B12.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'DM_WITH_2',
CASE WHEN B13.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'PARA_2',
CASE WHEN B14.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'TUMOR_2',
CASE WHEN B15.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'MOD_LIVER_3',
CASE WHEN B16.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'META_TUMOR_6',
CASE WHEN B17.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'AIDS_6',
CASE WHEN B18.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'DEPRESS',
CASE WHEN B19.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'ANEMIA',
CASE WHEN B20.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'PD',
CASE WHEN B21.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'LEUKE_2',
CASE WHEN B22.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'LYMPH_2',
CAST(BIRTH_DT AS DATE) AS DOB,
CAST(CONT_DT AS DATE) AS CONT,
CASE WHEN DEAD_DATE IS NULL OR DEAD_DATE = 'NA' THEN NULL
    ELSE cast(cast(cast(substring(DEAD_DATE, 1, len(DEAD_DATE)-4) as int) + 1911 as nvarchar) + right(DEAD_DATE,4) as date)
	END AS DEAD_DATE_1,
CASE WHEN D_DATE IS NULL OR D_DATE = 'NA' THEN NULL
    ELSE cast(cast(cast(substring(D_DATE, 1, len(D_DATE)-4) as int) + 1911 as nvarchar) + right(D_DATE,4) as date) 
	END AS D_DATE_1,
CASE WHEN IPD_DATE IS NULL OR IPD_DATE = 'NA' THEN NULL
    ELSE cast(cast(cast(substring(IPD_DATE, 1, len(IPD_DATE)-4) as int) + 1911 as nvarchar) + right(IPD_DATE,4) as date) 
	END AS IPD_DATE_1,
CASE WHEN CPD_DATE IS NULL OR CPD_DATE = 'NA' THEN NULL
    ELSE cast(cast(cast(substring(CPD_DATE, 1, len(CPD_DATE)-4) as int) + 1911 as nvarchar) + right(CPD_DATE,4) as date)
	END AS CPD_DATE_1,
CASE WHEN DIAG_DT IS NULL OR DIAG_DT = 'NA' THEN NULL
   ELSE CAST(DIAG_DT AS date)
END AS DIAG_DT_1
INTO LUNGCA_TUMOR_HIS_DATE
FROM LUNGCA_TUMOR_DATA A
LEFT JOIN LUNGCA_FINAL_HT B
ON A.FEE_NO = B.FEE_NO
AND A.ID_NO = B.ID_NO
LEFT JOIN LUNGCA_FINAL_DM_WITHOUT B1
ON A.FEE_NO = B1.FEE_NO
AND A.ID_NO = B1.ID_NO
LEFT JOIN LUNGCA_FINAL_HLP B2
ON A.FEE_NO = B2.FEE_NO
AND A.ID_NO = B2.ID_NO
LEFT JOIN LUNGCA_FINAL_CPD B3
ON A.FEE_NO = B3.FEE_NO
AND A.ID_NO = B3.ID_NO
LEFT JOIN LUNGCA_FINAL_RD B4
ON A.FEE_NO = B4.FEE_NO
AND A.ID_NO = B4.ID_NO
LEFT JOIN LUNGCA_FINAL_MI B5
ON A.FEE_NO = B5.FEE_NO
AND A.ID_NO = B5.ID_NO
LEFT JOIN LUNGCA_FINAL_CHF B6
ON A.FEE_NO = B6.FEE_NO
AND A.ID_NO = B6.ID_NO
LEFT JOIN LUNGCA_FINAL_CERE B7
ON A.FEE_NO = B7.FEE_NO
AND A.ID_NO = B7.ID_NO
LEFT JOIN LUNGCA_FINAL_DEME B8
ON A.FEE_NO = B8.FEE_NO
AND A.ID_NO = B8.ID_NO
LEFT JOIN LUNGCA_FINAL_RHEUM B9
ON A.FEE_NO = B9.FEE_NO
AND A.ID_NO = B9.ID_NO
LEFT JOIN LUNGCA_FINAL_PEPTIC B10
ON A.FEE_NO = B10.FEE_NO
AND A.ID_NO = B10.ID_NO
LEFT JOIN LUNGCA_FINAL_MILD_LIVER B11
ON A.FEE_NO = B11.FEE_NO
AND A.ID_NO = B11.ID_NO
LEFT JOIN LUNGCA_FINAL_DM_WITH B12
ON A.FEE_NO = B12.FEE_NO
AND A.ID_NO = B12.ID_NO
LEFT JOIN LUNGCA_FINAL_PARA B13
ON A.FEE_NO = B13.FEE_NO
AND A.ID_NO = B13.ID_NO
LEFT JOIN LUNGCA_FINAL_TUMOR B14
ON A.FEE_NO = B14.FEE_NO
AND A.ID_NO = B14.ID_NO
LEFT JOIN LUNGCA_FINAL_MOD_LIVER B15
ON A.FEE_NO = B15.FEE_NO
AND A.ID_NO = B15.ID_NO
LEFT JOIN LUNGCA_FINAL_META_TUMOR B16
ON A.FEE_NO = B16.FEE_NO
AND A.ID_NO = B16.ID_NO
LEFT JOIN LUNGCA_FINAL_AIDS B17
ON A.FEE_NO = B17.FEE_NO
AND A.ID_NO = B17.ID_NO
LEFT JOIN LUNGCA_FINAL_DEPRESS B18
ON A.FEE_NO = B18.FEE_NO
AND A.ID_NO = B18.ID_NO
LEFT JOIN LUNGCA_FINAL_ANEMIA B19
ON A.FEE_NO = B19.FEE_NO
AND A.ID_NO = B19.ID_NO
LEFT JOIN LUNGCA_FINAL_PD B20
ON A.FEE_NO = B20.FEE_NO
AND A.ID_NO = B20.ID_NO
LEFT JOIN LUNGCA_FINAL_LEUKE B21
ON A.FEE_NO = B21.FEE_NO
AND A.ID_NO = B21.ID_NO
LEFT JOIN LUNGCA_FINAL_LYMPH B22
ON A.FEE_NO = B22.FEE_NO
AND A.ID_NO = B22.ID_NO

SELECT DISTINCT ID_NO, FEE_NO, HB
INTO FINAL_ALL_LAB_HB
FROM (
    SELECT ID_NO,FEE_NO, HB FROM FINAL_S_LAB_HB
    UNION ALL
    SELECT ID_NO,FEE_NO, HB FROM FINAL_W_LAB_HB
    UNION ALL
    SELECT ID_NO,FEE_NO, HB FROM FINAL_T_LAB_HB
) AS combined_labs

SELECT DISTINCT ID_NO,FEE_NO, WBC
INTO FINAL_ALL_LAB_WBC
FROM (
    SELECT ID_NO,FEE_NO, WBC FROM FINAL_S_LAB_WBC
    UNION ALL
    SELECT ID_NO,FEE_NO, WBC FROM FINAL_W_LAB_WBC
    UNION ALL
    SELECT ID_NO,FEE_NO, WBC FROM FINAL_T_LAB_WBC
) AS combined_labs

SELECT DISTINCT ID_NO,FEE_NO, ALB
INTO FINAL_ALL_LAB_ALB
FROM (
    SELECT ID_NO,FEE_NO, ALB FROM FINAL_S_LAB_ALB
    UNION ALL
    SELECT ID_NO,FEE_NO, ALB FROM FINAL_W_LAB_ALB
    UNION ALL
    SELECT ID_NO,FEE_NO, ALB FROM FINAL_T_LAB_ALB
) AS combined_labs

SELECT DISTINCT ID_NO,FEE_NO, BUN
INTO FINAL_ALL_LAB_BUN
FROM (
    SELECT ID_NO,FEE_NO, BUN FROM FINAL_S_LAB_BUN
    UNION ALL
    SELECT ID_NO,FEE_NO, BUN FROM FINAL_W_LAB_BUN
    UNION ALL
    SELECT ID_NO,FEE_NO, BUN FROM FINAL_T_LAB_BUN
) AS combined_labs

SELECT distinct ID_NO,FEE_NO, CREA
INTO FINAL_ALL_LAB_CREA
FROM (
    SELECT ID_NO, FEE_NO, CREA FROM FINAL_S_LAB_CREA
    UNION ALL
    SELECT ID_NO,FEE_NO, CREA FROM FINAL_W_LAB_CREA
    UNION ALL
    SELECT ID_NO,FEE_NO, CREA FROM FINAL_T_LAB_CREA
) AS combined_labs


SELECT DISTINCT A.*, B.WBC
into FINAL_DATA_WBC
FROM FINAL_DATA_HB A
inner JOIN FINAL_ALL_LAB_WBC B
ON A.FEE_NO = B.FEE_NO

SELECT DISTINCT A.*, B.BUN
into FINAL_DATA_BUN
FROM FINAL_DATA_WBC A
inner JOIN FINAL_ALL_LAB_BUN B
ON A.FEE_NO = B.FEE_NO

SELECT DISTINCT A.*, B.CREA
--into FINAL_DATA_CREA
FROM FINAL_DATA_BUN A
inner JOIN FINAL_ALL_LAB_CREA B
ON A.FEE_NO = B.FEE_NO

SELECT DISTINCT A.*, B.HB, B1.WBC, B3.BUN, B4.CREA
FROM LUNGCA_TUMOR_HIS_DATE A
inner JOIN FINAL_ALL_LAB_HB B
ON A.FEE_NO = B.FEE_NO
AND A.ID_NO = B.ID_NO
inner JOIN FINAL_ALL_LAB_WBC B1
ON A.FEE_NO = B1.FEE_NO 
AND A.ID_NO = B1.ID_NO
--left JOIN FINAL_ALL_LAB_ALB B2
--ON A.FEE_NO = B2.FEE_NO 
--AND A.ID_NO = B2.ID_NO
inner JOIN FINAL_ALL_LAB_BUN B3
ON A.FEE_NO = B3.FEE_NO 
AND A.ID_NO = B3.ID_NO
inner JOIN FINAL_ALL_LAB_CREA B4
ON A.FEE_NO = B4.FEE_NO 
AND A.ID_NO = B4.ID_NO

SELECT DISTINCT A.*, B.HB, B1.WBC, B3.BUN, B4.CREA
FROM LUNGCA_TUMOR_HIS_DATE A
INNER JOIN FINAL_ALL_LAB_HB B
ON A.FEE_NO = B.FEE_NO
INNER JOIN FINAL_ALL_LAB_WBC B1
ON A.FEE_NO = B1.FEE_NO
INNER JOIN FINAL_ALL_LAB_BUN B3
ON A.FEE_NO = B3.FEE_NO
INNER JOIN FINAL_ALL_LAB_CREA B4
ON A.FEE_NO = B4.FEE_NO