SELECT DISTINCT A.*,
CASE WHEN B.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'HT',
CASE WHEN B1.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'DM_WITHOUT_1',
CASE WHEN B2.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'HLP',
CASE WHEN B3.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'CPD_1',
CASE WHEN B4.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'RENAL_2',
CASE WHEN B5.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'MI_1',
CASE WHEN B6.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'CHF_1',
CASE WHEN B7.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'CERE_1',
CASE WHEN B8.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'DEME_1',
CASE WHEN B9.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'RHEUM_1',
CASE WHEN B10.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'PEPTIC_1',
CASE WHEN B11.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'MILD_LIVER_1',
CASE WHEN B12.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'DM_WITH_2',
CASE WHEN B13.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'PARA_2',
CASE WHEN B14.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'TUMOR_2',
CASE WHEN B15.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'MOD_LIVER_3',
CASE WHEN B16.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'META_TUMOR_6',
CASE WHEN B17.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'AIDS_6',
CASE WHEN B18.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'DEPRESS',
CASE WHEN B19.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'ANEMIA',
CASE WHEN B20.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'PD',
CASE WHEN B21.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'LEUKE_2',
CASE WHEN B22.FEE_NO IS NOT NULL THEN 1 ELSE 0 END AS 'LYMPH_2',
INTO LUNGCA_TUMOR_HIS_DATE
FROM LUNGCA_TUMOR_DATA A
LEFT JOIN LUNGCA_FINAL_HT B
ON A.FEE_NO = B.FEE_NO
LEFT JOIN LUNGCA_FINAL_DM_WITHOUT B1
ON A.FEE_NO = B1.FEE_NO
LEFT JOIN LUNGCA_FINAL_HLP B2
ON A.FEE_NO = B2.FEE_NO
LEFT JOIN LUNGCA_FINAL_CPD B3
ON A.FEE_NO = B3.FEE_NO
LEFT JOIN LUNGCA_FINAL_RD B4
ON A.FEE_NO = B4.FEE_NO
LEFT JOIN LUNGCA_FINAL_MI B5
ON A.FEE_NO = B5.FEE_NO
LEFT JOIN LUNGCA_FINAL_CHF B6
ON A.FEE_NO = B6.FEE_NO
LEFT JOIN LUNGCA_FINAL_CERE B7
ON A.FEE_NO = B7.FEE_NO
LEFT JOIN LUNGCA_FINAL_DEME B8
ON A.FEE_NO = B8.FEE_NO
LEFT JOIN LUNGCA_FINAL_RHEUM B9
ON A.FEE_NO = B9.FEE_NO
LEFT JOIN LUNGCA_FINAL_PEPTIC B10
ON A.FEE_NO = B10.FEE_NO
LEFT JOIN LUNGCA_FINAL_MILD_LIVER B11
ON A.FEE_NO = B11.FEE_NO
LEFT JOIN LUNGCA_FINAL_DM_WITH B12
ON A.FEE_NO = B12.FEE_NO
LEFT JOIN LUNGCA_FINAL_PARA B13
ON A.FEE_NO = B13.FEE_NO
LEFT JOIN LUNGCA_FINAL_TUMOR B14
ON A.FEE_NO = B14.FEE_NO
LEFT JOIN LUNGCA_FINAL_MOD_LIVER B15
ON A.FEE_NO = B15.FEE_NO
LEFT JOIN LUNGCA_FINAL_META_TUMOR B16
ON A.FEE_NO = B16.FEE_NO
LEFT JOIN LUNGCA_FINAL_META_TUMOR B17
ON A.FEE_NO = B17.FEE_NO
LEFT JOIN LUNGCA_FINAL_DEPRESS B18
ON A.FEE_NO = B18.FEE_NO
LEFT JOIN LUNGCA_FINAL_ANEMIA B19
ON A.FEE_NO = B19.FEE_NO
LEFT JOIN LUNGCA_FINAL_PD B20
ON A.FEE_NO = B20.FEE_NO
LEFT JOIN LUNGCA_FINAL_LEUKE B21
ON A.FEE_NO = B21.FEE_NO
LEFT JOIN LUNGCA_FINAL_LYMPH B22
ON A.FEE_NO = B22.FEE_NO
