SELECT FEE_NO, HB
INTO FINAL_ALL_LAB_HB
FROM (
    SELECT FEE_NO, HB FROM FINAL_S_LAB_HB
    UNION ALL
    SELECT FEE_NO, HB FROM FINAL_W_LAB_HB
    UNION ALL
    SELECT FEE_NO, HB FROM FINAL_T_LAB_HB
) AS combined_labs

SELECT FEE_NO, WBC
INTO  FINAL_ALL_LAB_WBC
FROM (
    SELECT FEE_NO, WBC FROM FINAL_S_LAB_WBC
    UNION ALL
    SELECT FEE_NO, WBC FROM FINAL_W_LAB_WBC
    UNION ALL
    SELECT FEE_NO, WBC FROM FINAL_T_LAB_WBC
) AS combined_labs

SELECT FEE_NO, ALB
INTO FINAL_ALL_LAB_ALB
FROM (
    SELECT FEE_NO, ALB FROM FINAL_S_LAB_ALB
    UNION ALL
    SELECT FEE_NO, ALB FROM FINAL_W_LAB_ALB
    UNION ALL
    SELECT FEE_NO, ALB FROM FINAL_T_LAB_ALB
) AS combined_labs

SELECT FEE_NO, BUN
INTO FINAL_ALL_LAB_BUN
FROM (
    SELECT FEE_NO, BUN FROM FINAL_S_LAB_BUN
    UNION ALL
    SELECT FEE_NO, BUN FROM FINAL_W_LAB_BUN
    UNION ALL
    SELECT FEE_NO, BUN FROM FINAL_T_LAB_BUN
) AS combined_labs

SELECT distinct FEE_NO, CREA
INTO FINAL_ALL_LAB_CREA
FROM (
    SELECT FEE_NO, CREA FROM FINAL_S_LAB_CREA
    UNION ALL
    SELECT FEE_NO, CREA FROM FINAL_W_LAB_CREA
    UNION ALL
    SELECT FEE_NO, CREA FROM FINAL_T_LAB_CREA
) AS combined_labs
